# Container_Engine
#
# どちらか一方を選んで、有効化してください。
# Choose either one and enable it.  docker-ce or containerd
#container_engine: docker-ce
container_engine: containerd

# Kubernetes Package Version
#k8s_version: =1.9.6-00
#k8s_version: =1.10.3-00
#k8s_version: =1.11.2-00
#k8s_version: =1.12.5-00
#k8s_version: =1.13.2-00
#k8s_version: =1.14.3-00
#k8s_version: =1.15.0-00
#k8s_version: =1.16.0-00
#k8s_version: =1.16.3-00
k8s_version: =1.17.1-00

# Docker Package Version
docker_version: =18.06.1~ce~3-0~ubuntu

# Containerd version
containerd_version: 1.2.4

# K8s Minor Number
k8s_minor_ver: "{{ k8s_version.split('.')[1] }}"
