## kubeconfigディレクトリ作成
#
- name: mkdir kubeconfig
  file:
    path:  /home/vagrant/.kube
    state: directory
    owner: vagrant
    group: vagrant
    mode:  '0755'
- name: copy config to home dir
  copy:
    src:  /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes    
    owner: vagrant
    group: vagrant
    mode:  '0600'
